services:
  mysql-db:
    image: mysql:8.0
    networks:
      - veth-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${ROFISH_DB_USER}
      MYSQL_PASSWORD: ${ROFISH_DB_PASSWORD}
      MYSQL_DATABASE: ${ROFISH_DB}
    volumes:
      - rofish-db:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  veth-db:
    driver: bridge

volumes:
    rofish-db:
      driver: local
